### ISSUE TITLE
Is there a way to use this without being in a rails project?

### ISSUE THREAD

**Issue by Altonymous** [socialpandas/sidekiq-superworker#21]
If so how do I do it?   I noticed there's a generator and migrations that need to be run.

**Comment by adisos** [comment]
@tombenner 
Hi, I decided to not open new issue, but ask here. Is there way to start superworker outside of application, I mean put info to redis? In raw sidekiq I [can](https://github.com/mperham/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-rails) or structure is too complex?

**Comment by adisos** [comment]
I know, I can do like this:

```
class StartMySuperWorker
  include Sidekiq::Worker
 
 def perform(user_id)
    Superworker.create(:MySuperworker, :user_id) do
      OtherWorker :user_id
    end
  end
end
```
