### ISSUE TITLE
Sidekiq subjob ids remove from redis?

### ISSUE THREAD

**Issue by EMRJ** [socialpandas/sidekiq-superworker#34]
There are so much sidekiq subjob ids present in redis, Is there any way remove those ids other than FLUSHALL or Can I set timeout for those ids?

redis-cli:
2994) "subjob:e81406279e61b3cee8142744:1"
2995) "subjob:af9fef45dad8e9ec23031582:1"
2996) "subjob:b318436fcd37b4c0cfdbba0d:1"
2997) "subjob:6ee9724ec85d7d90cfccff45:2"
2998) "subjob:170614127898468942ef571f:1"
2999) "subjob:bb5b0479c620346170b89996:1"
3000) "subjob:c745adb8bfe2a1129e74d94e:1"
3001) "subjob:1e17236995937b079c45f68a:1"
3002) "subjob:40a48070370e6506b65babcf:1"
3003) "subjob:ceaebbb841456123880ba4f8:1

**Comment by AvonGenesis** [comment]
Did you ever find a solution to this?

**Comment by tombenner** [comment]
[Superjob expiration](https://github.com/socialpandas/sidekiq-superworker#superjob-expiration), which was somewhat recently added by @DarthMax (thanks, Max!), should handle this, but feel free to reopen if not.
